services:
  dealer-flow:
    build: . # Build the image from the Dockerfile in the current directory
    image: dealer-flow # Use the image tag you built
    container_name: dealer_flow_app
    env_file:
      - .env # Pass environment variables from .env file
    ports:
      - "8000:8000" # Map container port 8000 to host port 8000
    depends_on:
      - redis # Ensure Redis starts before the app
    networks:
      - dealer_net

  redis:
    image: redis:alpine # Use an official Redis image
    container_name: dealer_flow_redis
    # If you set a password in redis.conf and want to use it here:
    # command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - dealer_net
    # Optional: Persist Redis data outside the container
    # volumes:
    #   - redis_data:/data

networks:
  dealer_net:
    driver: bridge

# Optional: Define named volume for persistence
# volumes:
#   redis_data: